### ISSUE TITLE
build breaks with webpack.js

### ISSUE THREAD

**Issue by kdcro101** [radiovisual/html-colors#5]
When building project that imports `html-colors` using Webpack.js, build fails at
https://github.com/radiovisual/html-colors/blob/7b7be29ffd77f0a736bb826f0586bc898cbfc2a5/index.js#L3

Webpack is expecting `js` module.

To fix that,  `.json` extension is needed to be specified.

```js
const htmlColors = require('./html-colors.json');
```

**Comment by radiovisual** [comment]
This was fixed in the now published version `0.0.5` 👍 Thanks for reporting!
